# Generated by Django 5.1.6 on 2025-04-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Pampano St, Maya-Maya St, Malabon, Metro Manila'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.TextField(default='Not specified', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='interest',
            field=models.TextField(default='Not specified', max_length=50),
        ),
    ]
