# Generated by Django 5.1.6 on 2025-04-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_date_of_birth_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.TextField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.TextField(default=' ', max_length=50),
        ),
    ]
