# Generated by Django 5.1.6 on 2025-04-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_course_alter_student_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
