# Generated by Django 5.1.6 on 2025-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='Pampano St, Maya-Maya St, Malabon, Metro Manila', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
