# Generated by Django 5.1.6 on 2025-04-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_address_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default='Pampano St, Maya-Maya St, Malabon, Metro Manila'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.TextField(default=' ', max_length=50),
        ),
    ]
