# Generated by Django 5.1.6 on 2025-05-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_address_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='Pampano St, Maya-Maya St, Malabon, Metro Manila', max_length=50),
        ),
    ]
