# Generated by Django 5.1.6 on 2025-05-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
